name: Jest CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Install dependencies
        run: npm install
      - name: Jest
        run: npm install jest --global
      - name: install babel
        run: npm install --save-dev @babel/core
      - name: Run Jest
        run: jest
